

CREATE TABLE tt_tasks (
  task_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_name   VARCHAR2(200) NOT NULL,
  status      VARCHAR2(20) CHECK (status IN ('OPEN','IN_PROGRESS','DONE')),
  created_on  DATE DEFAULT SYSDATE
);


INSERT INTO tt_tasks (task_name, status) VALUES ('Create APEX app', 'OPEN');
COMMIT;

alter table tt_tasks
add description varchar2(100) null;
